// rafce
import React from 'react';
// import AboutBackground from "../Assets/about-background.png";
import Hero from "../../Assets/heroImage.png"
import AboutBackgroundImage from "../../Assets/about-background-image.png";
import { BsFillPlayCircleFill } from "react-icons/bs";


const About = () => {
  return (
    <div className="about-section-container" id='About'>
        {/* <div className="about-background-image-container">
            <img src={Hero} alt="" />
        </div> */}
    

        <div className="about-section-image-container">
            <img src={Hero} alt="" />
        </div>


        <div className="about-section-text-container">
            <p className="primary-subheading">About</p>

            <h1 className="primary-heading2">
            The Deep-fake Detector identify and mitigate 
            threats posed by manipulated content.
            </h1>


            <p className="primary-text">
            Generated by advanced machine learning models, poses risks in areas such as cybersecurity, misinformation, and privacy. 
            </p>

            <p className="primary-text">
            This tool helps users detect such manipulations efficiently and accurately, thereby ensuring trust and security.
            </p>

            <div className="about-buttons-container">
                <button className="secondary-button">Learn More</button>
                <button className="watch-video-button">
                    <BsFillPlayCircleFill /> Watch Video
                </button>
            </div>
        </div>
    </div>
  );
};

export default About;
